/*
 * @Author: chengbao.liu
 * @Date: 2022-02-21 14:42:32
 * @LastEditTime: 2022-03-14 17:00:29
 * @LastEditors: Please set LastEditors
 * @Description: 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
 * @FilePath: /zhongbang-web/pages/index.tsx
 */
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.scss'
import {
  footer_content,
  hot_business,
  information,
  main_service,
  my_company,
  nav_list,
  partner,
  product_list_five,
  product_list_four,
  product_list_one,
  product_list_six,
  product_list_three,
  product_list_two,
} from './api/common_data'
import {
  companyContentProps,
  companyProps,
  footerContentProps,
  informationContentProps,
  informationProps,
  mainServiceProps,
  partnerProps,
  productProps,
} from './index.data'

const Home: NextPage = () => {
  const [companyContent, setCompanyContent] = useState<companyProps>(
    my_company[0]
  )
  const [informationContent, setInformationContent] =
    useState<informationProps>(information[0])
  const [checkInformation, setCheckInformation] = useState<string>('工商服务')

  // 切换我的公司所处状态可以做的服务内容
  const handleMouseOver = (item: companyProps) => {
    setCompanyContent(item)
  }

  // 切换资讯的内容
  const handleInformationClick = (item: informationProps) => {
    setInformationContent(item)
    setCheckInformation(item.name)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.head_box}>
          <div className={styles.head}>
            <Image
              src={'/image/article_cover1.jpeg'}
              alt="噜噜尼企服"
              width={100}
              height={60}
            />
            <div className={styles.head_nav}>
              {nav_list.map((item: any, idx: number) => (
                <span key={'nag_list' + idx}>{item.title}</span>
              ))}
            </div>
          </div>
        </div>

        <div className={styles.main_service_box}>
          <div className={styles.main_service}>
            {main_service.map((item: mainServiceProps, idx: number) => (
              <div
                key={'mainservice' + idx}
                className={styles.main_service_item}
              >
                <Image
                  src={item.icon}
                  alt="噜噜尼企服"
                  width={60}
                  height={60}
                />
                <div>
                  <span className={styles.main_service_item_title}>
                    {item.title}
                  </span>
                  <span className={styles.main_service_item_text}>
                    {item.text}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className={styles.company_box}>
          <div className={styles.company}>
            {my_company.map((item: companyProps, idx: number) => (
              <div
                key={'company' + idx}
                className={styles.company_item}
                onMouseOver={() => handleMouseOver(item)}
              >
                <div className={styles.company_item_title}>{item.title}</div>
              </div>
            ))}
          </div>
          <div className={styles.company_item_content}>
            {companyContent.content.map(
              (item: companyContentProps, idx: number) => (
                <div key={'companyContent' + idx}>
                  <Image
                    src={item.icon}
                    className={styles.company_item_content_icon}
                    alt="噜噜尼企服"
                    width={126}
                    height={126}
                  />
                  <span className={styles.company_item_content_text}>
                    {item.text}
                  </span>
                </div>
              )
            )}
          </div>
        </div>
        <div className={styles.product_box}>
          <div className={styles.product_content}>
            <div className={styles.product1_left}>
              <p>科技项目申报</p>
              <span>中小企业公共服务示范平台</span>
              <span>十六年行业经验</span>
              <div>
                <span className={styles.product_tag}>
                  专精特新中小企业认定服务
                </span>
                <span className={styles.product_tag}>国家高新企业认定</span>
              </div>
            </div>
            <div className={styles.product_right}>
              {product_list_one.map((item: productProps, idx: number) => (
                <div
                  key={'product1' + idx}
                  className={styles.product_right_item}
                >
                  <div>
                    <div>
                      <p className={styles.product_right_item_title}>
                        {item.title}
                      </p>
                      <span className={styles.product_right_item_detail}>
                        {item.detail}
                      </span>
                    </div>
                    <div className={styles.product_right_item_tags}>
                      {item.tags.map((i: string, index: number) => (
                        <span key={'product1tag' + index}>{i}</span>
                      ))}
                    </div>
                  </div>
                  <div className={styles.product_right_item_price}>
                    <span>
                      {item.price === '面议' ? '面议' : '¥ ' + item.price}
                    </span>
                    {item.price !== '面议' && (
                      <span className={styles.product_right_item_price_tag}>
                        起
                      </span>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className={styles.product_box}>
          <div className={styles.product_content}>
            <div className={styles.product2_left}>
              <p>工商服务</p>
              <span>企业注册、变更、注销...</span>
              <span>一站式解决方案</span>
            </div>
            <div className={styles.product_right}>
              {product_list_two.map((item: productProps, idx: number) => (
                <div
                  key={'product2' + idx}
                  className={styles.product_right_item}
                >
                  <div>
                    <div>
                      <p className={styles.product_right_item_title}>
                        {item.title}
                      </p>
                      <span className={styles.product_right_item_detail}>
                        {item.detail}
                      </span>
                    </div>
                    <div className={styles.product_right_item_tags}>
                      {item.tags.map((i: string, index: number) => (
                        <span key={'product2tag' + index}>{i}</span>
                      ))}
                    </div>
                  </div>
                  <div className={styles.product_right_item_price}>
                    <span>
                      {item.price === '面议' ? '面议' : '¥ ' + item.price}
                    </span>
                    {item.price !== '面议' && (
                      <span className={styles.product_right_item_price_tag}>
                        起
                      </span>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className={styles.product_box}>
          <div className={styles.product_content}>
            <div className={styles.product3_left}>
              <p>财税服务</p>
              <span>专业会计团队助力</span>
              <span>省心省力</span>
              <div>
                <span className={styles.product_tag}>一般纳税人服务</span>
                <span className={styles.product_tag}>更多服务</span>
              </div>
            </div>
            <div className={styles.product_right}>
              {product_list_three.map((item: productProps, idx: number) => (
                <div
                  key={'product3' + idx}
                  className={styles.product_right_item}
                >
                  <div>
                    <div>
                      <p className={styles.product_right_item_title}>
                        {item.title}
                      </p>
                      <span className={styles.product_right_item_detail}>
                        {item.detail}
                      </span>
                    </div>
                    <div className={styles.product_right_item_tags}>
                      {item.tags.map((i: string, index: number) => (
                        <span key={'product3tag' + index}>{i}</span>
                      ))}
                    </div>
                  </div>
                  <div className={styles.product_right_item_price}>
                    <span>
                      {item.price === '面议' ? '面议' : '¥ ' + item.price}
                    </span>
                    {item.price !== '面议' && (
                      <span className={styles.product_right_item_price_tag}>
                        起
                      </span>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className={styles.product_box}>
          <div className={styles.product_content}>
            <div className={styles.product4_left}>
              <p>知识产权</p>
              <span>您的商标、专利、产品</span>
              <span>快速保护</span>
              <div>
                <span className={styles.product_tag}>发明专利申请</span>
                <span className={styles.product_tag}>商标撤三申请</span>
                <span className={styles.product_tag}>商标异议申请</span>
              </div>
            </div>
            <div className={styles.product_right}>
              {product_list_four.map((item: productProps, idx: number) => (
                <div
                  key={'product4' + idx}
                  className={styles.product_right_item}
                >
                  <div>
                    <div>
                      <p className={styles.product_right_item_title}>
                        {item.title}
                      </p>
                      <span className={styles.product_right_item_detail}>
                        {item.detail}
                      </span>
                    </div>
                    <div className={styles.product_right_item_tags}>
                      {item.tags.map((i: string, index: number) => (
                        <span key={'product4tag' + index}>{i}</span>
                      ))}
                    </div>
                  </div>
                  <div className={styles.product_right_item_price}>
                    <span>
                      {item.price === '面议' ? '面议' : '¥ ' + item.price}
                    </span>
                    {item.price !== '面议' && (
                      <span className={styles.product_right_item_price_tag}>
                        起
                      </span>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className={styles.product_box}>
          <div className={styles.product_content}>
            <div className={styles.product5_left}>
              <p>资质服务</p>
              <span>快速高通过率办理</span>
              <span>让你轻松拿证</span>
              <div>
                <span className={styles.product_tag}>SP经营许可证</span>
                <span className={styles.product_tag}>
                  互联网药品信息服务资格许可证
                </span>
                <span className={styles.product_tag}>食品经营许可证</span>
                <span className={styles.product_tag}>
                  广播电视节目制作经营许可证
                </span>
              </div>
            </div>
            <div className={styles.product_right}>
              {product_list_five.map((item: productProps, idx: number) => (
                <div
                  key={'product5' + idx}
                  className={styles.product_right_item}
                >
                  <div>
                    <div>
                      <p className={styles.product_right_item_title}>
                        {item.title}
                      </p>
                      <span className={styles.product_right_item_detail}>
                        {item.detail}
                      </span>
                    </div>
                    <div className={styles.product_right_item_tags}>
                      {item.tags.map((i: string, index: number) => (
                        <span key={'product5tag' + index}>{i}</span>
                      ))}
                    </div>
                  </div>
                  <div className={styles.product_right_item_price}>
                    <span>
                      {item.price === '面议' ? '面议' : '¥ ' + item.price}
                    </span>
                    {item.price !== '面议' && (
                      <span className={styles.product_right_item_price_tag}>
                        起
                      </span>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className={styles.product_box}>
          <div className={styles.product_content}>
            <div className={styles.product6_left}>
              <p>认证服务</p>
              <span>高新、体系认证、评级证书...</span>
              <span>一站式解决方案</span>
            </div>
            <div className={styles.product_right}>
              {product_list_six.map((item: productProps, idx: number) => (
                <div
                  key={'product6' + idx}
                  className={styles.product_right_item}
                >
                  <div>
                    <div>
                      <p className={styles.product_right_item_title}>
                        {item.title}
                      </p>
                      <span className={styles.product_right_item_detail}>
                        {item.detail}
                      </span>
                    </div>
                    <div className={styles.product_right_item_tags}>
                      {item.tags.map((i: string, index: number) => (
                        <span key={'product6tag' + index}>{i}</span>
                      ))}
                    </div>
                  </div>
                  <div className={styles.product_right_item_price}>
                    <span>
                      {item.price === '面议' ? '面议' : '¥ ' + item.price}
                    </span>
                    {item.price !== '面议' && (
                      <span className={styles.product_right_item_price_tag}>
                        起
                      </span>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className={styles.information_box}>
          <div>
            <div className={styles.information}>
              {information.map((item: informationProps, idx: number) => (
                <div
                  key={'information' + idx}
                  className={styles.information_item}
                  onClick={() => handleInformationClick(item)}
                  style={{
                    background:
                      checkInformation === item.name ? '#FFF' : '#F9F9F9',
                  }}
                >
                  <div className={styles.information_item_title}>
                    {item.name}
                  </div>
                </div>
              ))}
            </div>
            <div className={styles.information_item_content}>
              {informationContent.content.map(
                (item: informationContentProps, idx: number) => (
                  <div key={'informationContent' + idx}>
                    <Image
                      src={item.cover}
                      className={styles.information_item_content_icon}
                      alt="噜噜尼企服"
                      width={148}
                      height={84}
                    />
                    <div className={styles.information_item_content_right}>
                      <span className={styles.information_item_content_text}>
                        {item.title}
                      </span>
                      <span className={styles.information_item_content_intro}>
                        {item.intro}
                      </span>
                    </div>
                  </div>
                )
              )}
            </div>
          </div>
        </div>

        <div className={styles.partner_box}>
          <div className={styles.partner_title}>我们服务过的企业</div>
          <div className={styles.partner}>
            {partner.map((item: partnerProps, idx: number) => (
              <div key={'partner' + idx} className={styles.partner_item}>
                <Image
                  src={item.logo}
                  alt="噜噜尼企服"
                  height={item.height}
                  width={item.width}
                />
              </div>
            ))}
          </div>
        </div>
      </main>

      <footer className={styles.footer_box}>
        <div className={styles.footer}>
          <div className={styles.footer_top}>
            <div className={styles.footer_top_item}>
              <span className={styles.footer_top_title}>噜噜尼</span>
              <div>
                <span>客服热线</span>
                <span>400-123-456</span>
              </div>
              <div>
                <span>客服邮箱</span>
                <span>1601807915@qq.com</span>
              </div>
              <div className={styles.footer_top_item_contact}>
                <span>媒体采访</span>
                <span>1601807915@qq.com</span>
              </div>
              <div>
                <span>商务合作</span>
                <span>1601807915@qq.com</span>
              </div>
            </div>

            {footer_content.map((item: footerContentProps, idx: number) => (
              <div
                className={styles.footer_top_item}
                key={'footer_content' + idx}
              >
                <span className={styles.footer_top_title}>{item.title}</span>
                {item.list.map(
                  (item: { title: string; url: string }, index: number) => (
                    <div key={'footer_content_list' + idx + index}>
                      <span>{item.title}</span>
                    </div>
                  )
                )}
              </div>
            ))}

            <div className={styles.footer_work_time}>
              <p>400-123-456</p>
              <p>工作时间: 9:00-18:00</p>
            </div>
          </div>
          <div className={styles.footer_business}>
            <span>热门业务：</span>
            <div className={styles.footer_business_content}>
              {hot_business.map(
                (item: { title: string; url: string }, idx: number) => (
                  <span key={'hot_business' + idx}>{item.title}</span>
                )
              )}
            </div>
          </div>
          <div className={styles.footer_bottom}>
            <span>
              @2018-2022·上海噜噜尼企业咨询管理有限公司·版权所有ICP证：沪ICP备18026377号-1·
            </span>
            <span>沪公网安备 33019902000258号</span>
          </div>
        </div>
      </footer>
    </div>
  )
}

export default Home
